# =============================================================================
# MIGRATION TEMPLATE
# =============================================================================
# Alembic uses this template to generate new migration files.
# You don't need to modify this.
# =============================================================================

"""Add return_time

Revision ID: 2030636ad690
Revises: e13f6b9a4c21
Create Date: 2026-03-16 08:48:28.845347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2030636ad690'
down_revision: Union[str, None] = 'e13f6b9a4c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_incidents', sa.Column('return_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_incidents', 'return_time')
    # ### end Alembic commands ###
