# =============================================================================
# MIGRATION TEMPLATE
# =============================================================================
# Alembic uses this template to generate new migration files.
# You don't need to modify this.
# =============================================================================

"""Update staff table schema

Revision ID: ad45aed7988c
Revises: 
Create Date: 2026-02-03 12:30:13.715552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad45aed7988c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access levels')
    op.add_column('incidents', sa.Column('incident_date', sa.Date(), nullable=False))
    op.drop_column('incidents', 'date')
    op.add_column('registers', sa.Column('register_date', sa.Date(), nullable=False))
    op.drop_column('registers', 'date')
    op.add_column('staff', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('staff', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('staff', sa.Column('email', sa.String(length=150), nullable=False))
    op.add_column('staff', sa.Column('role', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'staff', ['email'])
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.create_foreign_key(None, 'staff', 'access_levels', ['role'], ['role'])
    op.drop_column('staff', 'name')
    op.drop_column('staff', 'hired_at')
    op.drop_column('staff', 'access_level')
    op.add_column('users', sa.Column('staff_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_foreign_key(None, 'users', 'staff', ['staff_id'], ['staff_id'])
    op.drop_column('users', 'phone')
    op.drop_column('users', 'email')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'id')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), nullable=False))
    op.add_column('users', sa.Column('id', sa.INTEGER(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DATETIME(), nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=100), nullable=False))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.drop_column('users', 'password')
    op.drop_column('users', 'staff_id')
    op.add_column('staff', sa.Column('access_level', sa.VARCHAR(length=50), nullable=False))
    op.add_column('staff', sa.Column('hired_at', sa.DATETIME(), nullable=False))
    op.add_column('staff', sa.Column('name', sa.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.create_foreign_key(None, 'staff', 'access levels', ['access_level'], ['role'])
    op.drop_constraint(None, 'staff', type_='unique')
    op.drop_column('staff', 'role')
    op.drop_column('staff', 'email')
    op.drop_column('staff', 'last_name')
    op.drop_column('staff', 'first_name')
    op.add_column('registers', sa.Column('date', sa.DATE(), nullable=False))
    op.drop_column('registers', 'register_date')
    op.add_column('incidents', sa.Column('date', sa.DATE(), nullable=False))
    op.drop_column('incidents', 'incident_date')
    op.create_table('access levels',
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('role')
    )
    # ### end Alembic commands ###
