# =============================================================================
# MIGRATION TEMPLATE
# =============================================================================
# Alembic uses this template to generate new migration files.
# You don't need to modify this.
# =============================================================================

"""Add site field to students

Revision ID: c4f2ea0f2b4f
Revises: ad45aed7988c
Create Date: 2026-02-16 16:15:45.517133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f2ea0f2b4f'
down_revision: Union[str, None] = 'ad45aed7988c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_levels',
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('site', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('year_group', sa.Integer(), nullable=True),
    sa.Column('has_disability', sa.Boolean(), nullable=False),
    sa.Column('disability_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['access_levels.role'], ),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('classes',
    sa.Column('class_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('users',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('class_students',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('class_id', 'student_id')
    )
    op.create_table('incidents',
    sa.Column('incident_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('duty_coordinator_id', sa.Integer(), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('other_activity', sa.String(length=200), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['duty_coordinator_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_table('registers',
    sa.Column('register_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('register_date', sa.Date(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.PrimaryKeyConstraint('register_id')
    )
    op.create_table('attendance',
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['register_id'], ['registers.register_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('register_id', 'student_id')
    )
    op.create_table('staff_incidents',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('staff_id', 'incident_id')
    )
    op.create_table('student_incidents',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('returned', sa.Boolean(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'incident_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_incidents')
    op.drop_table('staff_incidents')
    op.drop_table('attendance')
    op.drop_table('registers')
    op.drop_table('incidents')
    op.drop_table('class_students')
    op.drop_table('users')
    op.drop_table('classes')
    op.drop_table('staff')
    op.drop_table('students')
    op.drop_table('access_levels')
    # ### end Alembic commands ###
